const iso4217Currencies = [
  'AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS', 'AUD', 'AWG', 'AZN',
  'BAM', 'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BOV',
  'BRL', 'BSD', 'BTN', 'BWP', 'BYN', 'BZD', 'CAD', 'CDF', 'CHE', 'CHF',
  'CHW', 'CLF', 'CLP', 'CNY', 'COP', 'COU', 'CRC', 'CUP', 'CVE', 'CZK',
  'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'ERN', 'ETB', 'EUR', 'FJD', 'FKP',
  'GBP', 'GEL', 'GHS', 'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD', 'HNL',
  'HTG', 'HUF', 'IDR', 'ILS', 'INR', 'IQD', 'IRR', 'ISK', 'JMD', 'JOD',
  'JPY', 'KES', 'KGS', 'KHR', 'KMF', 'KPW', 'KRW', 'KWD', 'KYD', 'KZT',
  'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LYD', 'MAD', 'MDL', 'MGA', 'MKD',
  'MMK', 'MNT', 'MOP', 'MRU', 'MUR', 'MVR', 'MWK', 'MXN', 'MXV', 'MYR',
  'MZN', 'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD', 'OMR', 'PAB', 'PEN',
  'PGK', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF',
  'SAR', 'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLE', 'SLL', 'SOS',
  'SRD', 'SSP', 'STN', 'SVC', 'SYP', 'SZL', 'THB', 'TJS', 'TMT', 'TND',
  'TOP', 'TRY', 'TTD', 'TWD', 'TZS', 'UAH', 'UGX', 'USD', 'USN', 'UYI',
  'UYU', 'UYW', 'UZS', 'VED', 'VES', 'VND', 'VUV', 'WST', 'XAF', 'XAG',
  'XAU', 'XBA', 'XBB', 'XBC', 'XBD', 'XCD', 'XCG', 'XDR', 'XOF', 'XPD',
  'XPF', 'XPT', 'XSU', 'XTS', 'XUA', 'XXX', 'YER', 'ZAR', 'ZMW', 'ZWG',
];

export const defaultRules = [
  {
    id: 'invoice-number-required',
    name: 'Invoice number is required',
    type: 'required',
    fields: ['invoiceHeader.invoiceNumber'],
    params: {
      whenOtherFieldsPresent: ['invoiceHeader'],
      excludeField: 'invoiceNumber',
    },
    severity: 'error',
    message: 'Invoice number is missing.',
    enabled: true,
  },
  {
    id: 'invoice-date-not-future',
    name: 'Invoice date is not in the future',
    type: 'date_not_future',
    fields: ['invoiceHeader.invoiceDate'],
    params: {},
    severity: 'error',
    message: 'Invoice date cannot be in the future.',
    enabled: true,
  },
  {
    id: 'due-date-after-invoice-date',
    name: 'Due date is not before invoice date',
    type: 'date_order',
    fields: ['invoiceHeader.invoiceDate', 'invoiceHeader.dueDate'],
    params: { order: 'not_before' },
    severity: 'error',
    message: 'Due date cannot be before invoice date.',
    enabled: true,
  },
  {
    id: 'invoice-total-matches-subtotal-and-tax',
    name: 'Subtotal plus tax equals total due',
    type: 'sum_equals',
    fields: [
      'invoiceHeader.subtotalAmount',
      'invoiceHeader.taxAmount',
      'invoiceHeader.totalAmountDue',
    ],
    params: { tolerance: 0.02 },
    severity: 'error',
    message: 'Subtotal plus tax must equal the total amount due.',
    enabled: true,
  },
  {
    id: 'charge-line-subtotal-matches-quantity-and-price',
    name: 'Charge line subtotal matches quantity and unit price',
    type: 'product_equals',
    fields: [
      'shipmentDetails[].chargeLineItems[].quantity',
      'shipmentDetails[].chargeLineItems[].unitPriceRate',
      'shipmentDetails[].chargeLineItems[].lineSubtotal',
    ],
    params: { tolerance: 0.02 },
    severity: 'error',
    message: 'Quantity multiplied by unit price must equal the line subtotal.',
    enabled: true,
  },
  {
    id: 'charge-lines-match-invoice-subtotal',
    name: 'Charge line totals equal invoice subtotal',
    type: 'line_sum_equals',
    fields: [
      'invoiceHeader.subtotalAmount',
      'shipmentDetails[].chargeLineItems[].totalLineAmount',
    ],
    params: { tolerance: 0.02 },
    severity: 'warning',
    message: 'The sum of charge line totals should equal the invoice subtotal.',
    enabled: true,
  },
  {
    id: 'currency-is-valid-iso-4217',
    name: 'Currency is a valid ISO 4217 code',
    type: 'valid_currency',
    fields: ['invoiceHeader.currency'],
    params: { allowedCurrencies: iso4217Currencies },
    severity: 'error',
    message: 'Currency must be a valid 3-letter uppercase ISO 4217 code.',
    enabled: true,
  },
];

export default defaultRules;
